### ISSUE TITLE
Server is prone to crashing

### ISSUE THREAD

**Issue by redmie** [ankicommunity/anki-sync-server-rs#10]
The high number of unwrap in the code makes server fragile.
Even if no system related error happens (missing space, ... ) happens, encountering any malformed data will make the server crash we **MUST** fix that.

See pull request #9 for a step in the right direction

After the merge we will be down to:
```
parse.rs:0
error.rs:0
user.rs:2
main.rs:6
db.rs:0
sync.rs:29
schema.sql:0
media.rs:27
session.rs:0
```
Heavy work is still needed on `sync.rs` and `media.rs`.
@dobefore Could you do it in spirit of #9?
I'm currently saturated by a week of unwrap fixing on this project, that was not pleasant to say the least.

**Comment by dobefore** [comment]
hope this issue keep open,as the process is not yet finished even with the pr #14
