### ISSUE TITLE
Make dependence on rustls optional

### ISSUE THREAD

**Issue by redmie** [ankicommunity/anki-sync-server-rs#11]
I host on constrained resource behind a nginx reverse proxy that handles https.
As such I would benefit from having rustls as an optional dep. for reduced attack surface and smaller binary size.

This can be achieved by using cargo features flags (`#[cfg(...)]`)

**Comment by dobefore** [comment]
good point! I will give this a try.

**Comment by dobefore** [comment]
A pr has been made,hope you can give some advice,mainly in main.rs

**Comment by redmie** [comment]
Given my thoughts in the comment of #13.

Big thanks for your contribution and for the time you allocated to this project!
