### ISSUE TITLE
CI/CD system

### ISSUE THREAD

**Issue by redmie** [ankicommunity/anki-sync-server-rs#19]
Set up a CI system for build testing and QA before merging.

It is needed for #16 for example.
The CI must run pre-commit checks that will be introduced by #17.

**Comment by redmie** [comment]
I made a detailed review of MR #26 in its commen, please check it out!

@dobefore This is already very good work overall! Just some minor pains to rub out.

In another pull request we could target automatic container building and push image to a registry to solve problems mentioned in #16.

**Comment by dobefore** [comment]
automatic container building and push image to a registry #38
