### ISSUE TITLE
Logical error in sync.rs

### ISSUE THREAD

**Issue by redmie** [ankicommunity/anki-sync-server-rs#20]
In [sync.rs](https://github.com/redmie/anki-sync-server-rs/blob/1f43d7468830e0dbd6088310ea7086b61e82af90/src/sync.rs) in function `get_resp_data` line 384, the some of the branches of the if cannot be reached (as we unwrap on the checked result before this if).

We must replace this condition with pattern matching.

**Comment by dobefore** [comment]
I see no errors,reopen and make more detailed info if you wish.
