### ISSUE TITLE
Investigate easier to upgrade dependency on anki lib

### ISSUE THREAD

**Issue by redmie** [ankicommunity/anki-sync-server-rs#21]
For now the `anki` folder contains a patched copy of [anki](https://github.com/ankitects/anki) source code. We use its internal rust library inside our server. This will be difficult to keep the library updated (we need to as rusqlite and config version are starting to lag behind and cannot be upgraded without upgrading anki).

I propose keeping just a patch for the anki source code and depending on it either as a submodule we can `git apply` on, or via cargo integrated patching system (see [this](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section)).

[cargo patch](https://github.com/mettke/cargo-patch) would fit the bill nicely but I am wary of issues like [patch application](https://github.com/mettke/cargo-patch/issues/3) and [reliance on private changing apis](https://github.com/mettke/cargo-patch/issues/8). So I think that it is best we avoid it as our goal is to have an easy to maintain patch instead of the whole anki repository to take care of and upgrade.
As such mature tooling seems (to me at least) the way to go.

**Comment by redmie** [comment]
This will be fixed by the new changes introduced in MR #18. For now we are going the `git diff`/`git apply` route with an automated fetching via scripts but I am open to changes.

**Comment by dobefore** [comment]
Thanks for your thought on  it.Please correct me if I am wrong.

I am wondering that it appears to work if and only if patch file and anki library to be patched are both under the same commit id/tag? If so,it is of little use when code which is to be patched in anki library has changed its original position due to anki update.For example,
```
+1,3 @@
fn test() in patch file instruct patch target function should be located line 1

fn add_fn()
fn test()  here,test function changed it location,this will cause patch error
```

To be honest,I encounter patch error like `error: patch failed: rslib/src/backend/mod.rs:70` after running script `clone_patch_anki`,I think this is my fault bexause I made extra changes to anki.

Through inspecting patch file,I found there were approximately 5 functions and srveral structs to be patched..Work will largely be reduced if I move those structs  which were related to media sync to media.rs.And according to dae's comment,There will be media sync implementation in the near future [Media syncing with - - syncserver](https://forums.ankiweb.net/t/media-syncing-with-syncserver/15172)

So I intend to update anki manually and allow anki to be uploaded  to github after remove usused filed with extensions like `.py`,`.bzl`...

**Comment by dobefore** [comment]
Could you split MR #18 into two?One part about updating library and the other remain unchanged in MR #18

**Comment by dobefore** [comment]
@redmie ,Would you mind give me a chance to update anki iib manually only this time,as some apis in anki seem to change

**Comment by dobefore** [comment]
> Could you split MR #18 into two?One part about updating library and the other remain unchanged in MR #18.Because I want to test MR #26 after merging #18 .

no need to do this ,done in MR #27

**Comment by redmie** [comment]
Still if you really want to keep anki library in tree (which for the record I think is not a very good idea) please strip it bare. Just keep the rslib directory and remove all the non rust source files. I still think the script way is better. I implemented the windows script and updated the linux one in [better_clone_patch](https://github.com/redmie/anki-sync-server-rs/tree/better_clone_patch) branch as you merged #18 before I had time to push these changes here. It allows one to set an arbitrary anki repository via env variable.

___
About MR #27:

Backporting part of the anki library struct inside our source tree seems a bad idea to me as it makes upgrading once things starts changing inside the library a nightmare, it is bad practices to use our own type inside an outside library with the same types. Moreover what's the point of using a library if you are reimplementing it?

Please consider keeping anki out of source tree.

I don't see how patching is influenced by the platform it is done on as it relies on git which is platform independent.
To upgrade a patched anki to a new commit it is as simple as commiting the patched change on the currently tracked commit of anki then checkout anki master, pull to update repository then merge the commited change inside master and resolve merge conflict, verify it still build then generate a patch with something like `git diff origin/master`.

**Comment by dobefore** [comment]
> I implemented the windows script and updated the linux one in [better_clone_patch](https://github.com/redmie/anki-sync-server-rs/tree/better_clone_patch) branch as you merged #18 before I had time to push these changes here.

Sorry for this

I just encounter errors while applying your patch On windows like this
```
HEAD is now at 44342660d Update translations
error: patch failed: rslib/src/backend/mod.rs:70
error: rslib/src/backend/mod.rs: patch does not apply
```
have you test this patch?
If not I re-create a patch file in #27 
I generate patch file via following commands aproximately
```
git rev-parse HEAD #get original commitID
git commit #make changes to anki lib
git rev-parse HEAD #get current commit ID
git format-patch current_commitID -1
``` 
will this be the way you do?

**Comment by dobefore** [comment]
> I just encounter errors while applying your patch On windows like this
> 
> ```
> HEAD is now at 44342660d Update translations
> error: patch failed: rslib/src/backend/mod.rs:70
> error: rslib/src/backend/mod.rs: patch does not apply
> ```
> 
> have you test this patch?

It seems I found the reson why error appear.

patch file should use end of line sequence in LF instead of CRLF.

updating lib using patch way sure works briliant.So we go this way.
@redmie ,thank for your idea

**Comment by redmie** [comment]
Thanks for finding this bug @dobefore! I am not familiar with windows intrinsic and that seemed like a platform specific bug, you were right on that!
No offense taken for the speedy merge, I didn't give any feedback nor warn I would be implementing it. So its my fault :wink: 

If I understand well end of line should be unix (LF) and not windows (CRLF) like for the git patching to work?
Does it creates a problem when one wants to generate diff on windows?

Do you want me to open a MR for [better_clone_patch](https://github.com/redmie/anki-sync-server-rs/tree/better_clone_patch)?

**Comment by dobefore** [comment]
> If I understand well end of line should be unix (LF) and not windows (CRLF) like for the git patching to work?

yes,you are right!



> Does it creates a problem when one wants to generate diff on windows?

If I understand corectly you mean generate a patch file on windows?it is ok.I just generate a file ,yet it contain something like headersand foot.
```
From 480a572137a51316bab2d97f2435cdfe328c462c Mon Sep 17 00:00:00 2001
From: dobefore <1432338032@qq.com>
Date: Sun, 27 Mar 2022 11:09:31 +0800

......
-- 
2.28.0.windows.1
```
will this be normal,I havent test this file on linux?I am going to tonight



> Do you want me to open a MR for [better_clone_patch](https://github.com/redmie/anki-sync-server-rs/tree/better_clone_patch)?

It appear you have done a lot of work on [better_clone_patch](https://github.com/redmie/anki-sync-server-rs/tree/better_clone_patch),thanks.

Why not assign this to me?As this seems an easy work.I can continue work #27 
1.add warning on using patch file on windows to document
2....
Do you have something to add?@redmie

**Comment by redmie** [comment]
The work in [better_clone_patch](https://github.com/redmie/anki-sync-server-rs/tree/better_clone_patch) is not that much actually. It is an update of `scripts/clone_patch_anki`, the creation of an analog script for windows `scripts/clone_patch_anki.bat` and the update of `docs/INSTALL.md` to explain that one can use env variable to change anki repository path.

@dobefore I let you check and merge that as you so wish!
