### ISSUE TITLE
Docker build fails at prost-build (armv7h linux)

### ISSUE THREAD

**Issue by mktree** [ankicommunity/anki-sync-server-rs#22]
I tried out the docker build following your manual and it failed the process of setting up the builder. By the way I used docker and not podman.
The build failed at :
**Step 4/8 : RUN cargo build --release**
### Message:
<code>error: failed to run custom build command for `prost-build v0.7.0`

Caused by:
  process didn't exit successfully: `/usr/src/anki-sync-server-rs/target/release/build/prost-build-041e4c2d603755cc/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Failed to find the protoc binary. The PROTOC environment variable is not set, there is no bundled protoc for this platform, and protoc is not in the PATH', /usr/local/cargo/registry/src/github.com-1285ae84e5963aae/prost-build-0.7.0/build.rs:100:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
The command '/bin/sh -c cargo build --release' returned a non-zero code: 101</code>
### Solution:
I just checked what people suggested in case of such an error message and it seems that you just have to tell the debian-based rust-builder container to install protobuf-compiler (my thanks to David Maze from https://stackoverflow.com/a/65539101).
I added the command:

<code>RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive \
    apt-get install --no-install-recommends --assume-yes \
      protobuf-compiler</code>

to the Dockerfile right before _RUN cargo build --release_ 
This fixed the issue in my case and the build process finished successfully.

**Comment by dobefore** [comment]
Thanks for your exploring and sulotion.I have opened a PR which would bring your fix to respository.
