### ISSUE TITLE
different log info due to version bump

### ISSUE THREAD

**Issue by dobefore** [ankicommunity/anki-sync-server-rs#28]
Since MR #18 was merged ,actix-web seems to behave differently.
for example,following results are running on Windows intel 8 cores.

before merging,program appears to start 8 processes,yet this was reduced to 4 processes.
after #18 
```
[2022-03-27T13:11:34Z INFO  actix_server::builder] Starting 4 workers
[2022-03-27T13:11:34Z INFO  actix_server::server] Actix runtime found; starting in Actix runtime
```
before #18 
```

[2022-03-27T13:16:36Z INFO  actix_server::builder] Starting 8 workers
[2022-03-27T13:16:36Z INFO  actix_server::builder] Starting "actix-web-service-0.0.0.0:27701" service on 0.0.0.0:27701
```

**Comment by redmie** [comment]
Same on linux x86 with 8 logical cores, I got 4 workers. I think it is related to actix update.

After checking out code for [actix server builder](https://github.com/actix/actix-net/blob/855e3f96fe250d1cbba6acd49bdd6a4519c810b8/actix-server/src/builder.rs) it shows that actix launches the same number of processes that the number of **physical** cores and not the number of logical ones (so not the number of logical cores you obtain with hyper-threading). It makes sense as basically you cannot use more that your number of physical cores at 100% so no need for 2 times this number.

**Comment by dobefore** [comment]
Thanks for your answer.I got it!It seems that there are only four physical cores on my computers
