### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by redmie** [ankicommunity/anki-sync-server-rs#31]
Many functions have cryptic names like `get_md_mf` or `last_usn` for example.

It makes code maintenance hard as one struggles to find the function usage.
We should document what function does what and maybe explain the server architecture in a markdown file in `docs/`.

Could you help me on that @dobefore as you are the main contributor of the original server logic?

**Comment by dobefore** [comment]
> Many functions have cryptic names like `get_md_mf` or `last_usn` for example.

this is the truuth.I wll rename those functions and variables whose meanings are unclear like `get_md_mf` ,yet some are from anki lib ,although,I'll try to make it.

> We should document what function does what

this is what I am planning to do.I guess this is part of function comments with `\\\`?

> explain the server architecture in a markdown file in docs/

first,I describe the server architure in plain text ,then,If possible,can you re-process the material?
