### ISSUE TITLE
Use in memory database to manage sessions

### ISSUE THREAD

**Issue by redmie** [ankicommunity/anki-sync-server-rs#36]
Sessions do not need to survive server restart.
As such there is no need to keep them on disk (it's actually bad for both security and performance).

We should investigate the use of an in memory database for sessions.

Maybe something as simple as a rust `HashMap` would be sufficient, maybe we need something more powerful like [sled](https://github.com/spacejam/sled).

What are your thoughts on the subject @dobefore ?

**Comment by dobefore** [comment]
Thanks for the suggestion! It's possible to implement while seeing the anki lib  where that there is no database ops .

I'll take this,I

**Comment by dobefore** [comment]
I think I am wrong.Unfortunately there are still some conditions in which we have to rely on session on server restart.

We have to determine which user we are serving and that is only can be retrived from session database.And we look up username from session database  by `k` or `sk` from clent request.


Once we get username,then we can determine the corresponding collcection path.
