### ISSUE TITLE
Implement true arg parsing

### ISSUE THREAD

**Issue by redmie** [ankicommunity/anki-sync-server-rs#4]
The current argument parsing of `ankisyncd` is very limited.
We should leverage an arg parsing crate such as [clap](https://github.com/clap-rs/clap) in order to improve this.
It will allow for:
- help messages (using -h/--help)
- clean sub command for user management
- Configuration file path/parameter overwrite

If we use `clap` we should directly use `3.0.0-beta.5` as the v3 is nearing stable, will be supported longer than v2 and is much easier to work with than v2.

**Comment by dobefore** [comment]
thanks for recommending,it's sure suiaible.I will replace with it.

**Comment by dobefore** [comment]
Once finishing impl,I will open a pr and hope you can help review it.

**Comment by redmie** [comment]
> Once finishing impl,I will open a pr and hope you can help review it.

With pleasure!
