### ISSUE TITLE
How docker persists storage

### ISSUE THREAD

**Issue by Sagit-chu** [ankicommunity/anki-sync-server-rs#47]
How docker persists storage

**Comment by Sagit-chu** [comment]
If I mount /data, it reports an error
```
Error while getting configuration: IO error: No such file or directory (os error 2)
Error: ()
```

**Comment by dobefore** [comment]
Have you read the doc [here](https://github.com/ankicommunity/anki-sync-server-rs/blob/master/docs/CONTAINER.md#pull-image-from-hub-and-run-in-container)?

And this article  [使用 anki-sync-server-rs 部署自己的 anki 同步服务](https://www.bilibili.com/read/cv15441748/) may help

**Comment by Sagit-chu** [comment]
我看到dockerfile里面有配置文件，我提交了PR，用entrypoint.sh 判断一下是否挂载了配置文件，如果没有挂载就自动复制容器已经有的配置

**Comment by Sagit-chu** [comment]
这样方便使用和下游二次开发，我是在开发truecharts（truenas scale的应用）中看到这个情况

**Comment by dobefore** [comment]
感谢你的反馈。
然而你看下面代码
```
COPY --from=builder /usr/src/anki-sync-server-rs/scripts/ankisyncd.toml /app/ankisyncd.toml
```
是否和你提出的
···
if [ ! -f /app/ankisyncd.toml ]; then
	cp -u /ankisyncd.toml /app/ankisyncd.toml
fi
/usr/local/bin/ankisyncd -c /app/ankisyncd.toml
···
有异曲同工之效呢？
因为两者都是复制命令，前者没有失败的理由？

**Comment by dobefore** [comment]
感谢你的反馈。
然而你看下面代码
```
COPY --from=builder /usr/src/anki-sync-server-rs/scripts/ankisyncd.toml /app/ankisyncd.toml
```
是否和你提出的
···
if [ ! -f /app/ankisyncd.toml ]; then
	cp -u /ankisyncd.toml /app/ankisyncd.toml
fi
/usr/local/bin/ankisyncd -c /app/ankisyncd.toml
···
有异曲同工之效呢？
因为两者都是复制命令，前者没有失败的理由？

**Comment by Sagit-chu** [comment]
不一样，我写的是容器启动的时候执行命令，原来的是已经固定在容器里了，所以开机挂载一个空的是不会有配置文件的，而我的是一个脚本，开机执行一次复制到你的挂载点上。

**Comment by Sagit-chu** [comment]
这个方法很多镜像都用，就是为了在挂载的时候也可以生成想要的文件。而不会一挂载就变成空的，不挂载的时候是正常的

**Comment by dobefore** [comment]
不好意思，docker涉猎不深，冒昧问下，你是用的docker-compose吗，还是docker命令行呢

**Comment by Sagit-chu** [comment]
这两个没有区别吧。。

**Comment by Sagit-chu** [comment]
docker 和 K3S

**Comment by dobefore** [comment]
COPY --from=builder /usr/src/anki-sync-server-rs/scripts/ankisyncd.toml /app/ankisyncd.toml
那为什么把这条命令删除了呢

**Comment by Sagit-chu** [comment]
没有删除 只是改到根目录下，这样运行的时候从根下复制到/app下

**Comment by dobefore** [comment]
我大概理解了，感谢，学到了很多，我会尽快merge

**Comment by Sagit-chu** [comment]
好的~
