### ISSUE TITLE
when i migrate anki-sync-server to anki-sync-server-rs ,the anki client will get 500 http error 

### ISSUE THREAD

**Issue by snecker** [ankicommunity/anki-sync-server-rs#61]
thanks for the rust version ,it's a pretty useful version for me.

I've found a small problem
when i migrated the server from python 'anki-sync-server' to this rust version,the first time when i click "sync ", the client will get http  500 error

Then i logout my previous account, and retry to log in ,then it goes well。and

it appears both in ankidroid or  anki windows client，

I can solve it by logining again，but the better user experience i think is telling the user to login again (for example,show the logining dialog directly)

i've tried many version of anki-sync-server, your rust version is the only one that make me sync decks from pc to android successfully  , thx for your great job!

**Comment by dobefore** [comment]
Thanks for choosing this version !

I assume that you haven't created an account with this version of ankisyncd?

If possible and please ,could you post the server error log out here ?So that I can inspect the problem further.

**Comment by dobefore** [comment]
I have adjusted the code related to session part on your suggestions,so that authentication dialog will appear when the situation you have encountered emerges.#62

**Comment by snecker** [comment]
Thank you so much! I have tried the latest version and re-test it, It works now!
