### ISSUE TITLE
Users cannot be dynamically added/无法动态添加用户

### ISSUE THREAD

**Issue by zhaoying9105** [ankicommunity/anki-sync-server-rs#70]
After the following command is executed to add the user

./ankisyncd user --add username password

Synchronization cannot be performed through the anki client because the anki user is specified during server initialization. Can you change it to dynamic?

===========

执行了下面的命令添加用户之后

./ankisyncd user --add username password

无法通过anki 客户端执行同步，因为anki的用户是在server 初始化的时候指定的，可否修改成动态指定？

**Comment by dobefore** [comment]
Sure，try latest release version

**Comment by zhaoying9105** [comment]
Thanks a million!
